### ISSUE TITLE
Add a Footer Views to the `AccountOverview`

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziAccount#25]
### Problem

Some applications like the Spezi Template application could display some additional information such as licensing information or other settings at the bottom of the Account Overview. This information might be placed before or after the logout or delete button.

### Solution

Add a customizable footer (maybe two?) `ViewBuilder` customization points to the `AccountOverview` to add additional views to the `AccountOverview` that seamlessly integrate into the `AccountOverview`.

### Additional context

This feature might be useful for the https://github.com/StanfordSpezi/SpeziTemplateApplication/pull/36 PR to allow the position of the licensing information in the account overview.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by Supereg** [comment]
I think it definitely makes sense to add customization points for the `AccountOverview`, e.g., to add smaller sections like a `About` section to provide licensing information. I think, design wise, it makes sense to place it always above the Logout/Delete button (at least be that the primary thing; one could place some footnote text below the Logout/Delete button of course). 

Nonetheless, once this gets more cluttered (e.g. Help, Contact, Feedback Sections or even general settings or notifications settings) I would highly recommend to go for a dedictaed Settings Tab (or Sheet with same button placement) and making the `AccountOverview` a subview of that main settings view (e.g. via a prominent account header like in the Apple settings app). I don't think that for the long term it is sensible to mix account information with other settings or app information. Does that make sense?

**Comment by NikolaiMadlener** [comment]
In the end, it doesn't matter whether we **(1.)** include settings within the AccountOverview, or vice versa, **(2.)** include account information within a settings sheet/tab. I think that's just personal taste and every app does it differently. I believe if a developer wants to build either of them, they should find the right components in SpeziAccount for it. 
To ensure this, we could do the following:

- add footer components to AccountOverview as suggested by @PSchmiedmayer 
- implement an additional "AccountHeader" (or whatever you wanna call it) that looks something like in the Apple settings app as suggested by @Supereg 

Now one would have full flexibility. 

Also, if one chooses to implement option **(1.)** and the footer section would get too cluttered, one could still pass a NavigationLink to a dedicated settings page to the footer, right?
And, for option **(1.)**, one can just use the AccountHeader in the settings sheet/page (maybe as a NavigationLink to the AccountOverview)

Does that make sense?

**Comment by PSchmiedmayer** [comment]
Thank you for the PR @NikolaiMadlener, just reviewed it and provided a feedback on there. Thank you for taking a look at this and adding the nice header view; I like the approach 👍

**Comment by PSchmiedmayer** [comment]
Merged with the work done by @NikolaiMadlener in #27 🚀
