### ISSUE TITLE
XCTSpeziAccount

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziAccount#9]
### Problem

Creating UI tests for the Spezi Account package currently requires a significant level of UI testing code to achieve the login or sign-up functionality.

### Solution

XCTSpeziAccount should be a new target in the SpeziAccount module that automates the UI testing for SpeziAccount-related UI elements. By knowing insights into the Account Module and being used in the UI tests of the Account Module, we can simplify the UI testing flow for applications using the module.

An alternative or additional use case of the XCTSpeziAccount module could facilitate internal functions in SpeziAccount that allow one to skip the onboarding UI completely using a predefined set of command line arguments passed to the application under test.

### Additional context

A good first issue to get familiar with the framework and its testing infrastructure.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by Supereg** [comment]
We started this target with #76
